clusterName: "{{ .ClusterName }}"
clusterDescription: "E2E Test cluster"
organization: "{{ .Organization }}"

controlPlane:
  containerdVolume: {}
  etcdVolume: {}
  kubeletVolume: {}
  replicas: 3
  rootVolume: {}
  serviceAccount:
    email: default
    scopes:
    - https://www.googleapis.com/auth/compute
gcp:
  failureDomains:
  - europe-west3-a
  project: giantswarm-352614
  region: europe-west3
machineDeployments:
- containerdVolume: {}
  failureDomain: europe-west3-a
  instanceType: n1-standard-4
  kubeletVolume: {}
  name: worker0
  replicas: 3
  rootVolume:
    sizeGB: 100
  serviceAccount:
    email: default
    scopes:
    - https://www.googleapis.com/auth/compute
